name: PrintSiMi
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Creatively Yours
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212c5f'
    - '#f27934'
    - '#000033'
    - '#ff0000'
    - '#bf4000'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
