name: PrintSiMi
favicon: null
layout_spectrum: 0.2775890890043229
typography_spectrum: 0.8075533546507359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.17365545057691634
  lightness: 0.40417178510688245
  saturation: 0.3784780208952725
  rhythmicContrast: 0.9033911135047674
purpose: []
